version: '3.1'
services:
  stats-server:
    build: statistics-service/stats-server
    image: statistics-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-service:
    build: main-server
    container_name: main-server
    ports:
      - "8080:8080"
    depends_on:
      - statistics-service
      - main_db
    environment:
      - STATISTICS_SERVER.URL=http://statistics-service:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main_db:5432/postgres_main
  main-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root